del /q /s *.dcu
del /q /s *.exe
del /q /s *.dll
del /q /s *.cbk
del /q /s *.drc
del /q /s *.dsk
del /q /s *.dsm
del /q /s *.rsm
del /q /s *.identcache
del /q /s *.local
del /q /s *.map
del /q /s *.ico
del /q /s *.otares
del /q /s *.stat
rmdir /Q /S .\Samples\ZUGFeRD\__history
rmdir /Q /S .\Samples\ZUGFeRD\__recovery
rmdir /Q /S .\bin
rmdir /Q /S .\__history
rmdir /Q /S .\__recovery